### ISSUE TITLE
Route API not work in Laravel 6

### ISSUE THREAD

**Issue by nicolas-grzybowski** [mydnic/kanpen#14]
Hi,

I try to implement your package and use Vue Component but the route API return 404 error

**Comment by mydnic** [comment]
Good catch! There was a mistake in the Vue Component example
I fixed it in https://github.com/mydnic/laravel-subscribers/commit/c00f5643135ed01977ecc68fe29626f9055b311e

I just tagged v1.2.1 you will need to republish the component
Or just change `/api/subscriber` to `/subscribers-api/subscriber`
