### ISSUE TITLE
Any plans for a 'verify' feature

### ISSUE THREAD

**Issue by rabol** [mydnic/kanpen#25]
Any plans on adding an 'email verify' function to ensure that the email is vaild ?

**Comment by mydnic** [comment]
It's a good idea ! It should be an optional feature though.

I'm not planning to work actively on this package as I'm super busy at the moment.

I'll gladly accept any PR's and review them quickly

**Comment by rabol** [comment]
Would love to, but I don't know how to make the Nova part work

**Comment by mydnic** [comment]
@rabol there is probably nothing to do on that part. In any case I'll adapt if necessary

**Comment by mydnic** [comment]
Fixed, thanks for the PR!

**Comment by mydnic** [comment]
Note that I just updated the default config file to have the verify feature to false to prevent breaking changes
