### ISSUE TITLE
[Suggestion] Submit variable/text after confirmation

### ISSUE THREAD

**Issue by whollaus** [mydnic/kanpen#29]
Currently you are redirected to a specific page. But it would also be practical to transfer a variable to display something in the views.

redirect()->route(config('laravel-subscribers.redirect_url'))->with('verified', 'You are successfully subscribed to our list!');

Many thanks!

**Comment by mydnic** [comment]
@whollaus good catch 
It's done, I've tagged v1.4.0

**Comment by whollaus** [comment]
The change is also useful. But I mean something different. :)

In the verify function it would be helpful to send a return value. ->with('verified',....

This can be used, for example, to redirect to the start page and give the user feedback that he or she is now really signed for the newsletter. But it is important that it is a different variable than when store (e.g. subscribed and verified)

It would also be perfect if the text could be translated (also in the store function).  __('You are successfully subscribed to our list!')

**Comment by mydnic** [comment]
@whollaus could you maybe send a PR ?
Thanks 😄

**Comment by whollaus** [comment]
I hope it worked. I am not a github expert ;)
